version: '2'
services:
    invoice-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/invoice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=invoice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
